export type FormatMap = Record<string, string>;

export const FORMAT_MAP: FormatMap = {
  '123': 'mso123',
  '3gp': '3gpp',
  '3g2': '3gpp2',
  'ai': 'ai',
  'aiff': 'aiff',
  'asf': 'asf',
  'asp': 'asp',
  'asx': 'asx',
  'avi': 'avi',
  'bmp': 'bmp',
  'c': 'c',
  'cdf': 'cdf',
  'cpp': 'cpp',
  'css': 'css',
  'csv': 'csv',
  'dita': 'dita',
  'dng': 'dng',
  'doc': 'msword',
  'docm': 'msword12',
  'docx': 'msw12',
  'dot': 'msword',
  'dotx': 'msw12',
  'eml': 'eml',
  'eps': 'eps',
  'erf': 'erf',
  'exe': 'exe',
  'f4v': 'f4v',
  'flac': 'flac',
  'flv': 'flv',
  'gif': 'gif',
  'h': 'h',
  'htm': 'html',
  'html': 'html',
  'ico': 'ico',
  'ics': 'ics',
  'iso': 'iso',
  'jar': 'jar',
  'java': 'java',
  'jfif': 'jfif',
  'jp2': 'jp2',
  'jpe': 'jpeg',
  'jpeg': 'jpeg',
  'jpg': 'jpeg',
  'js': 'js',
  'json': 'json',
  'log': 'plain',
  'm4a': 'm4a',
  'm4v': 'm4v',
  'mid': 'midi',
  'midi': 'midi',
  'mkv': 'mkv',
  'mov': 'mov',
  'mp2': 'mp2',
  'mp3': 'mp3',
  'mp4': 'mp4',
  'mpeg': 'mpeg',
  'mpg': 'mpeg',
  'msi': 'msi',
  'nef': 'nef',
  'ods': 'ods',
  'odt': 'odt',
  'oga': 'oga',
  'ogg': 'ogg',
  'ogv': 'ogv',
  'orf': 'orf',
  'p12': 'p12',
  'p7b': 'p7b',
  'p7c': 'p7c',
  'p7m': 'p7m',
  'pdf': 'pdf',
  'php': 'php',
  'pl': 'pl',
  'png': 'png',
  'pot': 'msppt',
  'ppsm': 'msppt12',
  'ppsx': 'ppt12',
  'ppt': 'msppt',
  'pptm': 'msppt12',
  'pptx': 'ppt12',
  'ps': 'ps',
  'psd': 'psd',
  'py': 'py',
  'ra': 'ra',
  'ram': 'ram',
  'rdf': 'rdf',
  'rm': 'rm',
  'rpm': 'rpm',
  'rss': 'rss',
  'rtf': 'rtf',
  'rw2': 'rw2',
  'sh': 'sh',
  'shtml': 'html',
  'sql': 'sql',
  'svg': 'svg',
  'swf': 'swf',
  'tar': 'tar',
  'tif': 'tiff',
  'tiff': 'tiff',
  'tgz': 'tgz',
  'thmx': 'thmx',
  'ts': 'ts',
  'tsv': 'tsv',
  'ttf': 'ttf',
  'txt': 'plain',
  'vcf': 'vcf',
  'vob': 'vob',
  'vsd': 'vsd',
  'wav': 'wav',
  'wma': 'wma',
  'wmv': 'wmv',
  'wpd': 'wpd',
  'wps': 'wps',
  'wsdl': 'wsdl',
  'xhtml': 'html',
  'xla': 'msexcel',
  'xlam': 'xlam',
  'xls': 'msexcel',
  'xlsb': 'xl12',
  'xlsm': 'xl12',
  'xlsx': 'xl12',
  'xlt': 'msexcel',
  'xltx': 'xl12',
  'xml': 'xml',
  'xps': 'xps',
  'zip': 'zip',
};

export function getDocumentumFormat(extension: string): string {
  const ext = extension.replace(/^\./, '').toLowerCase();
  return FORMAT_MAP[ext] ?? ext;
}

export function getExtensionFromFilename(filename: string): string | null {
  const dotIndex = filename.lastIndexOf('.');
  if (dotIndex === -1 || dotIndex === filename.length - 1) {
    return null;
  }
  return filename.substring(dotIndex + 1).toLowerCase();
}
